#!/usr/bin/env python3
"""Build the LIFE ZERO Observer Office page from shared organizational state.

The page is a view. `observer/state.json` is the data, and it is the only thing
that should change between builds -- the agents write state, the observer reads
it. Editing the generated HTML by hand defeats that and will be overwritten.

    python3 scripts/build_observer.py          # build, then publish office.html
    python3 scripts/build_observer.py --check  # validate state.json only
"""

import argparse
import datetime
import io
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from company_clock import clock  # noqa: E402  -- the 7:1 ratio, one definition

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE = os.path.join(REPO, "observer", "state.json")
INVENTORY = os.path.join(REPO, "state", "inventory.json")
TEMPLATE = os.path.join(REPO, "observer", "office.template.html")
OUT = os.path.join(REPO, "observer", "office.html")
MARKER = "__LIFEZERO_STATE__"

REQUIRED_AGENT = ["id", "display", "role", "room", "status", "avatar",
                  "current_task", "why", "schedule", "next_run", "priority"]
STATUSES = {"WORKING", "RESEARCHING", "WAITING", "BLOCKED", "ERROR", "IDLE", "REVENUE"}


def fail(msg):
    print("FAIL: " + msg)
    return False


def validate(s):
    """Catch the failure this page must never have: showing something untrue."""
    ok = True
    rooms = {r["id"] for r in s.get("rooms", [])}
    gates = {g["id"] for g in s.get("gates", [])}
    agents = {a.get("id") for a in s.get("agents", [])}

    for a in s.get("agents", []):
        who = a.get("id", "?")
        for k in REQUIRED_AGENT:
            if a.get(k) in (None, "") and not (k == "next_run" and a.get("next_run") is None):
                ok = fail("agent %s is missing %s" % (who, k))
        if a.get("status") not in STATUSES:
            ok = fail("agent %s has unknown status %r" % (who, a.get("status")))
        if a.get("room") not in rooms:
            ok = fail("agent %s sits in unknown room %r" % (who, a.get("room")))
        b = a.get("blocked_by")
        if b and b not in gates and b != "egress":
            ok = fail("agent %s is blocked by unknown gate %r" % (who, b))
        if a.get("status") == "BLOCKED" and not b:
            ok = fail("agent %s shows BLOCKED but names nothing blocking it" % who)
        if b and a.get("status") != "BLOCKED":
            ok = fail("agent %s names a blocker but does not show BLOCKED" % who)
        if a.get("runs") == 0 and a.get("accomplished"):
            ok = fail("agent %s has never run but claims accomplishments" % who)

    for e in s.get("feed", []):
        if e.get("who") not in agents:
            ok = fail("feed event at %s is attributed to unknown agent %r"
                      % (e.get("t"), e.get("who")))
    for m in s.get("messages", []):
        if m.get("from") not in agents:
            ok = fail("message %r is from unknown agent %r" % (m.get("subject"), m.get("from")))
        if m.get("to") not in agents and m.get("to") != "all":
            ok = fail("message %r is to unknown agent %r" % (m.get("subject"), m.get("to")))

    # What we sell is NOT hand-written state. It is generated by scripts/inventory.py
    # straight from the shop, because this page once listed six products while nine were
    # live and nobody could see the gap (KB-173). If the two disagree, the page is wrong
    # about its own inventory and must not be built.
    if not os.path.exists(INVENTORY):
        ok = fail("state/inventory.json does not exist. Run scripts/inventory.py -- the "
                  "product list is generated from the shop, never typed here.")
    else:
        with io.open(INVENTORY, encoding="utf-8") as fh:
            inv = json.load(fh)
        if s.get("products") != inv.get("products"):
            here = {p.get("url") for p in s.get("products", [])}
            real = {p.get("url") for p in inv.get("products", [])}
            for u in sorted(real - here):
                ok = fail("%s is for sale and this page does not list it" % u)
            for u in sorted(here - real):
                ok = fail("this page lists %s and it is not for sale" % u)
            if here == real:
                ok = fail("the product list matches by address but differs in detail from "
                          "state/inventory.json. Re-run scripts/inventory.py rather than "
                          "editing observer/state.json by hand.")
        age_days = (datetime.datetime.now(datetime.timezone.utc) -
                    datetime.datetime.fromisoformat(inv["generated_at"])).days
        if age_days > 7:
            ok = fail("the inventory was last read from the shop %d days ago. Re-run "
                      "scripts/inventory.py; a stale product list is how this went wrong "
                      "before." % age_days)

    # A GATE ID IS NEVER REUSED, BECAUSE THE CHAIRMAN'S ANSWERS OUTLIVE THE GATE.
    #
    # His Done / Couldn't do it / Later lands in a store keyed by gate id and stays
    # there. On 2026-10-01 two new gates were given the ids gate-1 and gate-2, and the
    # store still held a gate-1 from 2026-09-26 marked **blocked** -- a withdrawn ask
    # about messaging people he knows. The CEO prompt calls a blocked row the
    # highest-value row on the page, so the next cycle would have read a three-day-old
    # answer to a different question as the chairman having tried today's gate and
    # failed, and acted on it. Nothing would have looked wrong.
    led_path = os.path.join(REPO, "state", "gate_ids.json")
    if s.get("gates"):
        try:
            with io.open(led_path, encoding="utf-8") as fh:
                seen = json.load(fh).get("seen", {})
        except (IOError, OSError, ValueError):
            seen = {}
        for g in s["gates"]:
            gid, title = g.get("id"), g.get("title", "")
            if not gid:
                ok = fail("a gate carries no id, so the chairman's answer has nowhere to land")
                continue
            was = seen.get(gid)
            if was is not None and was != title:
                ok = fail("gate id %r was already used for %r and now means %r. His answer to the "
                          "old one is still in the store under that id and would be read as an "
                          "answer to this one. Give it a new id; never reuse."
                          % (gid, was[:60], title[:60]))

    # THE PANELS THAT MUST BE REWRITTEN ROT; THE ONES THAT ARE APPENDED TO DO NOT.
    #
    # The chairman, 2026-09-30: "the game is not reflecting the adjustments we made."
    # The activity feed was current to the minute, because every cycle appends to it.
    # The summary panels above it -- the ones he reads first -- were four days stale:
    # the marketplace listing still read "built and blocked" six days after it went
    # live and four days after it became the company's one bet. Nothing was lying;
    # nobody had rewritten them, and the busy feed underneath made the page look
    # maintained. So each of them now carries the date it was last rewritten, and this
    # refuses to build when one has gone stale. At 7:1, three human days is
    # twenty-one company days -- long enough to be deliberate, short enough to hurt.
    MAX_PANEL_AGE_DAYS = 3
    today = datetime.date.today()
    for field in ("ventures", "strategy"):
        for i, row in enumerate(s.get(field, [])):
            label = row.get("name") or row.get("ref") or ("%s[%d]" % (field, i))
            stamp = row.get("as_of")
            if not stamp:
                ok = fail("%s \u2014 %r carries no as_of date, so nobody can tell whether it is "
                          "current. Rewrite it and stamp it." % (field, label))
                continue
            try:
                age = (today - datetime.date.fromisoformat(stamp)).days
            except ValueError:
                ok = fail("%s \u2014 %r has an as_of of %r, which is not a date." % (field, label, stamp))
                continue
            if age > MAX_PANEL_AGE_DAYS:
                ok = fail("%s \u2014 %r was last rewritten %d days ago (%d company days). "
                          "Re-read it against what is true now and stamp it, or the chairman "
                          "reads a summary the feed underneath already contradicts."
                          % (field, label, age, age * 7))

    sb = s.get("scoreboard", {})
    if sb.get("revenue", 0) != sb.get("profit", 0) + sb.get("expenses", 0):
        ok = fail("scoreboard does not balance: revenue != profit + expenses")
    if sb.get("revenue", 0) > 0 and not sb.get("revenue_ever"):
        ok = fail("revenue is above zero but revenue_ever is false")
    if sb.get("customers", 0) == 0 and sb.get("revenue", 0) > 0:
        ok = fail("revenue with no customers -- one of the two is wrong")
    claimed = sum(a.get("revenue_attributed") or 0 for a in s.get("agents", []))
    if claimed != sb.get("revenue", 0):
        ok = fail("agents claim $%s of revenue but the scoreboard says $%s"
                  % (claimed, sb.get("revenue", 0)))
    if sb.get("active_agents") != len(s.get("agents", [])):
        ok = fail("scoreboard says %s agents; %s are defined"
                  % (sb.get("active_agents"), len(s.get("agents", []))))
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate state.json and stop")
    args = ap.parse_args()

    with io.open(STATE, encoding="utf-8") as fh:
        s = json.load(fh)

    # The company runs seven days to the owner's one (chairman, 2026-09-26).
    # Stamped here so the public page and every reader agree; the office page
    # recomputes it live from the viewer's clock so it never goes stale.
    s["meta"]["clock"] = clock()
    s["meta"]["day"] = s["meta"]["clock"]["company_days"]

    if not validate(s):
        sys.exit("\nstate.json describes an organization that cannot exist. "
                 "Fix the state, not the page.")
    print("state.json is consistent: %d agents, %d gates, %d events, %d buried."
          % (len(s.get("agents", [])), len(s.get("gates", [])),
             len(s.get("feed", [])), len(s.get("graveyard", []))))

    # WHEN THIS PAGE WAS BUILT IS NOT SOMETHING ANYONE TYPES.
    #
    # It used to live in state.json by hand, and on 2026-09-30 the chairman said the
    # page was "not reflecting the adjustments we made" -- because it was stamped
    # 2026-09-29 20:05 while carrying that morning's work. Every word on it was
    # current; the one number he actually looks at said yesterday. There was a stale
    # warning here, set at 36 hours, and the stamp was 12 hours old, so it never fired
    # and would not have been read if it had. The build knows this value exactly.
    # Charter rule 3: never type a fact into the office that a system already knows.
    was = s["meta"].get("generated_at")
    s["meta"]["generated_at"] = datetime.datetime.now(
        datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    if was != s["meta"]["generated_at"]:
        with io.open(STATE, "w", encoding="utf-8") as fh:
            json.dump(s, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
    print("stamped %s (was %s)" % (s["meta"]["generated_at"], was))

    if args.check:
        return

    with io.open(TEMPLATE, encoding="utf-8") as fh:
        tpl = fh.read()
    if MARKER not in tpl:
        sys.exit("FAIL: template has no %s marker" % MARKER)

    # </script> inside the JSON would close the host <script> tag early.
    blob = json.dumps(s, ensure_ascii=False).replace("</", "<\\/")
    with io.open(OUT, "w", encoding="utf-8") as fh:
        fh.write(tpl.replace(MARKER, blob))
    print("wrote %s (%.1f KB)" % (os.path.relpath(OUT, REPO), os.path.getsize(OUT) / 1024.0))
    print("Now publish it with the Artifact tool, capabilities {sample:{}, db:{}}.")


if __name__ == "__main__":
    main()
