#!/usr/bin/env python3
"""Directive ledger: acknowledge an owner directive once, execute it once.

On 2026-09-24 the same 11,536-character directive was delivered twice, 85 minutes
apart, byte-identical. It was executed twice. The cost was duplicated
reorganization work and a merge conflict with a sibling agent.

Before acting on any owner directive, hash it here. If it is already in the
ledger, acknowledge it and DO NOT re-execute -- report what was already done.

    python3 scripts/directive.py check  <file>     # already known?
    python3 scripts/directive.py record <file> --title "..." --summary "..."
    python3 scripts/directive.py list
"""

import argparse
import datetime
import hashlib
import io
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(REPO, "org", "directives.json")
DOC = os.path.join(REPO, "org", "DIRECTIVES.md")


def normalise(t):
    """Ignore whitespace and case so a re-paste with a stray newline still matches."""
    return re.sub(r"\s+", " ", t).strip().lower()


def directive_id(text):
    return "D-" + hashlib.sha256(normalise(text).encode("utf-8")).hexdigest()[:10]


def load():
    try:
        with io.open(LEDGER, encoding="utf-8") as fh:
            return json.load(fh)
    except (IOError, OSError, ValueError):
        return {"directives": []}


def save(d):
    with io.open(LEDGER, "w", encoding="utf-8") as fh:
        json.dump(d, fh, indent=2, ensure_ascii=False, sort_keys=True)
        fh.write("\n")


def render(d):
    lines = ["# OWNER DIRECTIVES — what has already been incorporated", "",
             "Generated by `scripts/directive.py`. Do not edit by hand.", "",
             "**A directive already listed here has been executed. Acknowledge it and report",
             "what was done — do not re-execute it.** Re-running a reorganization directive",
             "does not reorganize twice; it duplicates work and collides with sibling agents.",
             ""]
    for x in sorted(d["directives"], key=lambda r: r["first_seen"]):
        lines += ["## %s — %s" % (x["id"], x["title"]), "",
                  "- **First received:** %s" % x["first_seen"],
                  "- **Deliveries:** %d%s" % (x["deliveries"],
                      (" (last %s)" % x["last_seen"]) if x["deliveries"] > 1 else ""),
                  "- **Length:** %d characters" % x["chars"],
                  "- **Status:** %s" % x["status"], "",
                  x["summary"], ""]
    with io.open(DOC, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["check", "record", "list"])
    ap.add_argument("path", nargs="?")
    ap.add_argument("--title", default="")
    ap.add_argument("--summary", default="")
    ap.add_argument("--status", default="incorporated")
    a = ap.parse_args()

    d = load()
    if a.action == "list":
        for x in sorted(d["directives"], key=lambda r: r["first_seen"]):
            print("%s  x%-2d  %s  %s" % (x["id"], x["deliveries"], x["first_seen"][:16],
                                         x["title"]))
        return 0

    if not a.path:
        sys.exit("need a file containing the directive text")
    with io.open(a.path, encoding="utf-8") as fh:
        text = fh.read()
    did = directive_id(text)
    known = [x for x in d["directives"] if x["id"] == did]
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    if a.action == "check":
        if known:
            k = known[0]
            print("ALREADY INCORPORATED: %s — %s" % (k["id"], k["title"]))
            print("First received %s, %d deliveries, status %s."
                  % (k["first_seen"], k["deliveries"], k["status"]))
            print("\nAcknowledge it and report what was already done. Do NOT re-execute.")
            return 1
        print("NEW: %s. Not previously seen. Execute it, then record it." % did)
        return 0

    if known:
        k = known[0]
        k["deliveries"] += 1
        k["last_seen"] = now
        save(d); render(d)
        print("%s was already recorded. Delivery #%d noted; nothing re-executed."
              % (did, k["deliveries"]))
        return 1

    d["directives"].append({
        "id": did, "title": a.title or os.path.basename(a.path),
        "summary": a.summary, "status": a.status,
        "first_seen": now, "last_seen": now, "deliveries": 1, "chars": len(text),
    })
    save(d); render(d)
    print("recorded %s" % did)
    return 0


if __name__ == "__main__":
    sys.exit(main())
